### PR TITLE
fix: NODE_LOADER_CONFIG for absolute paths

### PR DESCRIPTION
**Pull request by johnloy**
When specifying an absolute system path for `NODE_LOADER_CONFIG`, this change allows that path to be used, instead of joining it with `process.cwd()`.

Tests ✅ after this change.

### CODE REVIEW

**Review by joeldenning — APPROVED** [review]
Thanks for your contribution.

The tests don't cover the NODE_LOADER_CONFIG env variable, I don't think, so them passing doesn't show that this entirely works. The code looks good, though, so I'll merge this and test locally before publishing a new version.

**Comment by joeldenning** [comment]
Ah this added a package-lock.json file, which it should not have. I will remove that in a subsequent commit.

**Comment by joeldenning** [comment]
I fixed the issues with the lock files, among a couple other small maintenance things, in #3. Everything's released in https://github.com/node-loader/node-loader-core/releases/tag/v1.0.4

**Comment by johnloy** [comment]
Thanks so much for the speedy release! Also, I appreciate your great work on this and your other import maps packages.

In case it's of interest, I'm using this and @node-loader/import-maps in https://github.com/johnloy/static-shadow-dom. I hope to be publishing within a few days, and will be sure to give you a README thanks there once I do.

If you'd like, I could also contribute a test for the env variable?

Cheers!

**Comment by joeldenning** [comment]
Great to hear you are using this project in static-shadow-dom. Yes, if you'd like to add a test for the NODE_LOADER_CONFIG env variable that would be great.

**Pull request merged**
